[".config/zsh/completions/chezmoi.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/twpayne/chezmoi/master/completions/chezmoi.zsh"
    refreshPeriod = "168h"

[".config/zsh/completions/zoxide-zsh-completion"]
    type = "git-repo"
    url = "https://github.com/jnooree/zoxide-zsh-completion.git"
    refreshPeriod = "168h"
    stripComponents = 1

[".config/zsh/completions/_eza"]
    type = "file"
    url = "https://raw.githubusercontent.com/eza-community/eza/main/completions/zsh/_eza"
    refreshPeriod = "168h"

[".config/zsh/completions/_yabai"]
    type = "file"
    url = "https://raw.githubusercontent.com/Amar1729/yabai-zsh-completions/main/src/_yabai"
    refreshPeriod = "168h"

# Broken - Accepts suggestions under a number of circumstances without doing so explicitly
[".config/zsh/plugins/zsh-autosuggestions.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/zsh-users/zsh-autosuggestions/master/zsh-autosuggestions.zsh"
    refreshPeriod = "168h"

[".config/zsh/plugins/navi.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/denisidoro/navi/master/shell/navi.plugin.zsh"
    refreshPeriod = "168h"

[".config/zsh/plugins/zsh-ssh.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/sunlei/zsh-ssh/master/zsh-ssh.zsh"
    refreshPeriod = "168h"

[".config/zsh/plugins/fzf-tab"]
    type = "git-repo"
    url = "https://github.com/Aloxaf/fzf-tab.git"
    refreshPeriod = "168h"
    stripComponents = 1

[".config/zsh/plugins/fast-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zdharma-continuum/fast-syntax-highlighting"
    refreshPeriod = "168h"
    stripComponents = 1

[".config/zsh/plugins/fzf-tab-source"]
    type = "git-repo"
    url = "https://github.com/Freed-Wu/fzf-tab-source"
    refreshPeriod = "168h"
    stripComponents = 1



